org: danipoav
app: api
service: subscriptions-api

provider:
  name: aws
  runtime: nodejs22.x
  region: eu-west-3
  stage: dev
  environment:
    NODE_ENV: production
    SECRET_KEY: ${env:SECRET_KEY}
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}

functions:
  api:
    handler: dist/app.handler
    events:
      - httpApi: "*"

package:
  include:
    - dist/**
